### ISSUE TITLE
Dubbel

### ISSUE THREAD

**Issue by Tindyy** [OniWithTheHoodie/the-startup-responsive-interactieve-website#2]
https://github.com/OniWithTheHoodie/the-startup-responsive-interactieve-website/blob/26920bb2be7b8c66210bbc75524c47297bf803a6/assets/style.css#L32-L43

**Comment by OniWithTheHoodie** [comment]
fixed is eruit gehaald

**Comment by OniWithTheHoodie** [comment]
fixed is eruit gehaald

**Comment by OniWithTheHoodie** [comment]
is gefixt en eruit gehaald 

```css

@media  only screen and  (max-width: 50em ) {

  body {
    display: flex;
    flex-direction: column;
  }
```

**Comment by OniWithTheHoodie** [comment]
is gefixt en eruit gehaald 

```css

@media  only screen and  (max-width: 50em ) {

  body {
    display: flex;
    flex-direction: column;
  }
```
