### ISSUE TITLE
Mobile first design gebruik dan min-width

### ISSUE THREAD

**Issue by Patrickkhr** [OniWithTheHoodie/the-startup-responsive-interactieve-website#3]
https://github.com/OniWithTheHoodie/the-startup-responsive-interactieve-website/blob/26920bb2be7b8c66210bbc75524c47297bf803a6/assets/style.css#L38

**Comment by OniWithTheHoodie** [comment]
Ik heb het eruit gehaald en nu heeft mijn mobile geen media query maar voor desktop zal er breakpoint aan toegvoegd worden vanuit mobiel. 

```css
/* mobile first */

  body {
    display: flex;
    flex-direction: column;
  }

  nav{
    display: flex;
    flex-direction: row;
    gap: 1.5em;
    border-bottom: 0.1em solid var(--black);
    padding: 0em 0em 1em 1em;
    margin: 1em 0em 2em 0em;
  }

  h2{
    font-size: medium;
    margin: 0.1em;
  }

  .triangle-left {
    width: 0;
    height: 0;
    border-top: 0.4em solid transparent;
    border-right: 0.5em solid #555;
    border-bottom: 0.4em solid transparent;
    margin: 0.5em 0 0 01em;

    & .triangle-text {
      position: relative;
      top: -2.6em;
      left: 0.5em;
      font-family: var(--paragraaf-font-family);
      font-size: var(--paragraaf-font-size);
      font-weight: var(--paragraaf-font-weight);
      line-height: var(--paragraaf-font-line-height);
      color: var(--black);
    }
}

    h1  {
      font-family: var(--heading-1-font-family);
      font-size: var(--heading-1-font-size);
      font-weight: var(--heading-1-font-weight);
      line-height: var(--heading-1-line-height);
      margin: 2em 0 0 0.6em;
      color: var(--black);
    }
  
    .highlight {
      font-family: var(--paragraaf-font-family);
      font-size: var(--paragraaf-font-size);
      font-weight: var(--paragraaf-font-weight);
      line-height: var(--paragraaf-font-line-height);
      color: var(--white);
      background-color: var(--black);
      width: 6em;
      text-align: center;
      margin: 2em 0 0 0.6em;
    }

    .context {
      font-family: var(--paragraaf-font-family);
      font-size: var(--paragraaf-font-size);
      font-weight: var(--paragraaf-font-weight);
      line-height: var(--paragraaf-font-line-height);
      margin: 2em 0 0 0.6em;
    }

    p {
      font-family: var(--paragraaf-font-family);
      font-size: var(--paragraaf-font-size);
      font-weight: var(--paragraaf-font-weight);
      line-height: var(--paragraaf-font-line-height);
      margin: 2em 0 0 0.6em;
    }

    /* pijl uitklap links */
    .arrow {
      border: solid black;
      border-width: 0 3px 3px 0;
      display: inline-block;
      padding: 3px;
    }

    .down {
      transform: rotate(45deg);
      -webkit-transform: rotate(45deg);
      margin: 2em 0 0 0.6em;
      cursor: pointer;
    }

    .arrow-text {
      position: relative;
      top: -3em;
      left: 1.3em;
      font-family: var(--paragraaf-font-family);
      font-size: var(--paragraaf-font-size);
      font-weight: var(--paragraaf-font-weight);
      line-height: var(--paragraaf-font-line-height);
    }
    
    .line {
      border-top: 0.2em solid var(--black);
      width: 55em;
      height: 1em;
      rotate: 90deg;
      position: relative;
      top: 26em;
      right: 27em;
    }


    .bar-links {
      display: flex;
      flex-direction: column;
      gap: 1.5em;
      position: relative;
      left: 2.5em;
      top: 1em;
    }

    .bar-links > a {
      color: var(--black);
      font-family: var(--paragraaf-font-family);
      font-size: var(--paragraaf-font-size);
      font-weight: var(--paragraaf-font-weight);
      line-height: var(--paragraaf-font-line-height);
    }

    .sub-link {
      position: relative;
      left: 1em;
    }

    /* INTERACTION */
    .hidden {
      display: none;
    }

    .up {
      transform: rotate(0deg);
      -webkit-transform: rotate(0deg);
    }

    /* footer */
    footer {
      border-top: 0.1em solid var(--black);
      margin-top: 9em;
    }

    .footer-content {
      margin-top: 1.5em;
      display: flex;
      flex-direction: column;
      gap: 1em;
    }

    .footer-content > a {
      color: var(--black);
      color: var(--black);
      font-family: var(--paragraaf-font-family);
      font-size: var(--paragraaf-font-size);
      font-weight: var(--paragraaf-font-weight);
      line-height: var(--paragraaf-font-line-height);
      margin-left: 1em;
      text-decoration: none;
    }

    .seperate-link {
      color: var(--black);
    }

```
